# Generated by Django 5.2.16 on 2026-07-19 11:23

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=80)),
                ('preferred_units', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2)),
                ('bodyweight_unit', models.CharField(choices=[('kg', 'kg'), ('st_lb', 'st & lb'), ('lb', 'lb')], default='kg', max_length=5)),
                ('bodyweight_goal_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('share_history', models.BooleanField(default=False)),
                ('plate_inventory', models.JSONField(default=apps.accounts.models.default_plate_inventory)),
                ('deload_after_failures', models.PositiveSmallIntegerField(default=3)),
                ('deload_percent', models.DecimalField(decimal_places=1, default=10, max_digits=4)),
                ('deload_week_percent', models.DecimalField(decimal_places=1, default=50, max_digits=4)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=6)),
                ('pseudonym', models.CharField(max_length=40, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
