# Generated by Django 5.2.16 on 2026-07-19 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('curated', 'Curated')], default='private', max_length=7)),
                ('archived', models.BooleanField(default=False)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='routines.routine')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('superset_group', models.PositiveIntegerField(blank=True, null=True)),
                ('target_sets', models.PositiveSmallIntegerField()),
                ('target_reps_low', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_reps_high', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('superset_rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_set_amrap', models.BooleanField(default=False)),
                ('target_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('target_distance_m', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('progression_style', models.CharField(choices=[('none', 'None'), ('double', 'Double progression'), ('linear', 'Linear progression')], default='double', max_length=6)),
                ('progression_increment_kg', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routine')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RoutineRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visibility', 'curated'), ('owner__isnull', True)), models.Q(models.Q(('visibility', 'curated'), _negated=True), ('owner__isnull', False)), _connector='OR'), name='curated_iff_ownerless'),
        ),
        migrations.AddConstraint(
            model_name='routinerotation',
            constraint=models.UniqueConstraint(fields=('user', 'routine'), name='routine_once_per_rotation'),
        ),
    ]
