# Generated by Django 5.2.16 on 2026-07-20 07:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('session_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('set_type', models.CharField(choices=[('normal', 'Normal'), ('warmup', 'Warm-up'), ('dropset', 'Drop set')], default='normal', max_length=7)),
                ('superset_group', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='', max_length=5)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('_load_type', models.CharField(default='external', editable=False, max_length=15)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='logbook.workoutsession')),
            ],
            options={
                'ordering': ['position', 'completed_at'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CardioLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('treadmill', 'Treadmill'), ('bike', 'Bike'), ('rower', 'Rower'), ('stairmaster', 'Stairmaster'), ('outdoor_run', 'Outdoor run'), ('walk', 'Walk'), ('swim', 'Swim'), ('other', 'Other')], max_length=12)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('distance_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('performed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardio', to='logbook.workoutsession')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'started_at'], name='logbook_wor_user_id_2e585c_idx'),
        ),
        migrations.AddIndex(
            model_name='setlog',
            index=models.Index(fields=['exercise', 'session'], name='logbook_set_exercis_07cb58_idx'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gte', 0), ('_load_type', 'bodyweight_plus'), _connector='OR'), name='negative_weight_only_bodyweight_plus'),
        ),
        migrations.AddIndex(
            model_name='cardiolog',
            index=models.Index(fields=['user', 'performed_at'], name='logbook_car_user_id_be79f3_idx'),
        ),
    ]
