# Generated by Django 5.2.16 on 2026-07-19 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('force', models.CharField(blank=True, choices=[('push', 'Push'), ('pull', 'Pull'), ('static', 'Static')], default='', max_length=6)),
                ('mechanic', models.CharField(blank=True, choices=[('compound', 'Compound'), ('isolation', 'Isolation')], default='', max_length=9)),
                ('equipment', models.CharField(blank=True, default='', max_length=60)),
                ('load_type', models.CharField(choices=[('external', 'External load'), ('bodyweight_plus', 'Bodyweight plus added load')], default='external', max_length=15)),
                ('bar_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metric', models.CharField(choices=[('weight_reps', 'Weight x reps'), ('weight_time', 'Weight x time'), ('weight_distance_time', 'Weight x distance (x time)')], default='weight_reps', max_length=20)),
                ('unilateral', models.BooleanField(default=False)),
                ('is_mobility', models.BooleanField(default=False)),
                ('dots_eligible', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, default='')),
                ('image_paths', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('custom', 'Custom')], default='custom', max_length=6)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], max_length=9)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.musclegroup')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(related_name='exercises', through='exercises.ExerciseMuscle', to='exercises.musclegroup'),
        ),
        migrations.AddConstraint(
            model_name='exercisemuscle',
            constraint=models.UniqueConstraint(fields=('exercise', 'muscle_group'), name='one_role_per_exercise_muscle'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('bar_weight_kg__isnull', True), ('load_type', 'external'), _connector='OR'), name='bar_weight_only_on_external'),
        ),
    ]
